#' extractSpectrum
#' 
#' Extract spectral data along with metadata from JSON files generated by ExfilMS (https://github.com/vmalnathnambiar/exfilms).
#' 
#' Metadata extraction only applicable to data acquired at the Australian National Phenome Centre (ANPC).
#' 
#' @import jsonlite
#' 
#' @export
#' @param input Input path (can be a directory or a single file) containing input files for extraction: character
#' @param inputFiles A vector of input files for extraction: character vector
#' @returns A list containing two data frames (samples that passed and failed the extraction process)
#' 
#' @examples
#' input <- "/path/to/input/directory/"
#' result <- ticq::extractSpectrum(input = input, 
#'                                 inputFiles = ticq::retrieveFileList(input = input, fileExtension = "JSON"))
extractSpectrum <- function(input, inputFiles) {
  # Set defaults
  passedData <- data.frame()
  failedFileList <- character(0)
  
  # If input is NOT NULL and there are JSON files for extraction
  if (!is.null(input) && length(inputFiles) > 0) {
    # Determine if input is a directory or a file
    fileInfo <- file.info(input)
    
    # Loop input file list for extraction
    for (i in inputFiles) {
      # Determine path to file
      if (fileInfo$isdir) {
        filePath <- paste0(input, i)
      } else {
        filePath <- input
      }
      
      # Extract metadata and spectrum data from JSON file
      sample <- tryCatch(jsonlite::fromJSON(filePath),
                         warning = function(w) NULL,
                         error = function(e) NULL)
      
      # If no error / warning occurred during extraction
      if (!is.null(sample)) {
        # Extract metadata
        sampleInfo <- ticq::extractMetadata(input = filePath)
        
        # Append data to data frame
        passedData <- rbind(passedData, 
                            data.frame(sampleID = sample$id,
                                       project = sampleInfo$project,
                                       cohort = sampleInfo$cohort,
                                       projectCohort = sampleInfo$projectCohort,
                                       matrix = sampleInfo$matrix,
                                       sampleType = sampleInfo$sampleType,
                                       method = sampleInfo$method,
                                       instrument = sampleInfo$instrument,
                                       plate = sampleInfo$plate,
                                       date = sample$date,
                                       time = sample$time,
                                       spectrumCount = sample$spectrumCount,
                                       spectrum = sample$spectrum))
      } else {
        # Add file name to the failed file list
        failedFileList <- c(failedFileList, i)
      }
    }
  }
  
  return(list(passedData = passedData,
              failedData = as.data.frame(failedFileList)))
}