#' extractSpectrum
#'
#' Extract spectral data from JSON files generated by ExfilMS (https://github.com/vmalnathnambiar/exfilms) along with the metadata (based on input path).
#'
#' Metadata extraction only applicable to data acquired at the Australian National Phenome Centre (ANPC).
#'
#' @import jsonlite
#'
#' @export
#' @param input Input path (can either a directory or a single file path) containing input files for extraction: character
#' @param inputFiles Input files to be extracted: character vector
#' @returns List containing two data frames (passed and failed data)
extractSpectrum <- function(input, inputFiles) {
  # Defaults
  passedData <- data.frame()
  failedFileList <- character(0)
  
  # If input is NOT NULL and there are JSON files for extraction
  if (!is.null(input) && length(inputFiles) > 0) {
    # Extract file information (to check if input is a directory or file)
    fileInfo <- file.info(input)
    
    # Loop input file list for extraction
    for (i in inputFiles) {
      # Check and determine path to file
      if (fileInfo$isdir) {
        filePath <- paste0(input, i)
      } else {
        filePath <- input
      }
      
      # Extract metadata and spectrum data from JSON file
      sample <- tryCatch(jsonlite::fromJSON(filePath),
                         warning = function(w) NULL,
                         error = function(e) NULL)
      
      # Check if error / warning occurred during JSON extraction
      if (!is.null(sample)) {
        # Extract metadata
        sampleInfo <- ticq::extractMetadata(input = filePath)
        
        # Append data to data frame
        passedData <- rbind(passedData,
                            data.frame(sampleID = sample$id,
                                       project = sampleInfo$project,
                                       cohort = sampleInfo$cohort,
                                       projectCohort = sampleInfo$projectCohort,
                                       matrix = sampleInfo$matrix,
                                       sampleType = sampleInfo$sampleType,
                                       method = sampleInfo$method,
                                       instrument = sampleInfo$instrument,
                                       plate = sampleInfo$plate,
                                       date = sample$date,
                                       time = sample$time,
                                       spectrumCount = sample$spectrumCount,
                                       spectrum = sample$spectrum))
      } else {
        # Add file name to failed file list
        failedFileList <- c(failedFileList, i)
      }
    }
  }
  
  return(list(passedData = passedData,
              failedData = as.data.frame(failedFileList)))
}