#' Extract ExfilMS
#'
#' Extract spectral data from JSON files generated using ExfilMS (https://github.com/vmalnathnambiar/exfilms). Also includes retrievable metadata from sample name or file path.
#'
#' Metadata extraction only applicable to data acquired at the Australian National Phenome Centre (ANPC).
#'
#' To evaluate target m/z with TICQ, perform targeted spectra filtering using ExfilMS. The target file used for ExfilMS should match the target file defined in TICQ for comparison
#'
#' @import jsonlite
#'
#' @export
#' @param inputPath Input path to JSON files generated by ExfilMS: character
#' @returns A list containing two data frames (passed and failed data)
extractExfilMS <- function(inputPath) {
  # Defaults
  passedData <- data.frame()
  fileName <- character(0)
  
  # Retrieve JSON file names
  inputFiles <- ticq::retrieveFileName(inputPath = inputPath, fileExtension = "JSON")
  
  # Check input files
  if (length(inputFiles) > 0) {
    # Loop through input files
    for (i in inputFiles) {
      # Determine file path
      filePath <- if (file.info(inputPath)$isdir) paste0(inputPath, i) else inputPath
      
      # Extract spectral data
      sample <- tryCatch(jsonlite::fromJSON(filePath), warning = function(w) NULL, error = function(e) NULL)
      
      if (!is.null(sample)) {
        # Extract metadata
        sampleInfo <- ticq::extractMetadata(input = filePath)
        
        # Append data
        passedData <- rbind(
          passedData,
          data.frame(
            sampleID = sample$id,
            project = sampleInfo$project,
            cohort = sampleInfo$cohort,
            projectCohort = sampleInfo$projectCohort,
            matrix = sampleInfo$matrix,
            sampleType = sampleInfo$sampleType,
            method = sampleInfo$method,
            instrument = sampleInfo$instrument,
            plate = sampleInfo$plate,
            date = sample$date,
            time = sample$time,
            timestamp = as.POSIXct(paste(sample$date, sample$time)),
            spectrumCount = sample$spectrumCount,
            spectrum = sample$spectrum
          )
        )
      } else {
        fileName <- c(fileName, i)
      }
    }
  }
  
  return(list(passedData = passedData, failedData = as.data.frame(fileName)))
}