#' Render TICQ Assessment
#' 
#' Perform TICQ assessment on MS spectral data acquired from JSON files generated using ExfilMS (https://github.com/vmalnathnambiar/exfilms) and render a HTML report of the assessment.
#' 
#' Metadata extraction and anonymisation only applicable to data acquired at the Australian National Phenome Centre (ANPC).
#' 
#' To evaluate extracted ions (target m/z) with TICQ, spectral data generated by ExfilMS should have undergone targeted spectra filtering during extraction to JSON using a target file or an in-house ANPC method library. The same target file or ANPC method library should be specified in TICQ for a comprehensive assessment. 
#' 
#' Historical spectral data used for comparison should have also undergone the same extraction/spectra filtering process previously as the current spectral data being assessed. Historical data should be made available in RDS format for reading.
#' Use ticq::extractExfilMS() to extract spectral data from ExfilMS generated JSON files to have the same data structure required for TICQ, and save data using saveRDS().
#' 
#' Chromatogram region can be configured using ticq::configureChromatogramRegion(). If no chromatogram region is provided, TICQ will attempt to configure the chromatogram region data using the ANPC method library specified.
#' 
#' @import httr
#' @import rmarkdown
#' 
#' @export
#' @param inputPath Input path to JSON files generated by ExfilMS: character
#' @param outputDirectoryPath Output directory path to save HTML report and spectral data RDS output (Default: /output/folder/in/current/working/directory/): character
#' @param historicalDataPath Historical data (RDS format) path containing spectral data for comparison (Default: NULL): NULL or character
#' @param targetFilePath Published to web URL or local path of the TSV formatted target file (Default: NULL, Options: Published to web URL or local file path): NULL or character
#' @param anpcMethodLibrary ANPC method library (Default: NULL, Options: "MS-AA-POS", "MS-HIL-POS", "MS-HIL-NEG", "MS-RP-POS" or "MS-RP-NEG"): NULL or character
#' @param chromatogramRegion A list containing the start and end time points of the different chromatogram regions of interest (Default: NULL, Options: ticq::configureChromatogramRegion()): NULL or list
#' @param roundDecimalPlace Number of decimal places for precision value rounding (Default: NULL): NULL or numeric
#' @param metadataAnonymiser Toggle to anonymise metadata (Default: FALSE, Options: TRUE or FALSE): logical
renderTICQ <- function(inputPath, outputDirectoryPath = paste0(getwd(), "/output/"), historicalDataPath = NULL, targetFilePath = NULL, anpcMethodLibrary = NULL, chromatogramRegion = NULL, roundDecimalPlace = NULL, metadataAnonymiser = FALSE) {
  # Chromatogram region data patterns and associated ANPC method library representation
  pattern <- c("prewash", "massCalibration", "analyte", "wash")
  anpcChromatogramRegionData <- list(
    "MS-AA-POS" = list(massCalibrationStart = 0, massCalibrationEnd = 0.3, washStart = 5),
    "MS-HIL-POS" = list(massCalibrationStart = 0, massCalibrationEnd = 0.7, washStart = 11),
    "MS-HIL-NEG" = list(massCalibrationStart = 0, massCalibrationEnd = 0.7, washStart = 11),
    "MS-RP-POS" = list(massCalibrationStart = 0, massCalibrationEnd = 0.7, washStart = 11),
    "MS-RP-NEG" = list(massCalibrationStart = 0, massCalibrationEnd = 0.7, washStart = 11)
  )
  
  # Validate parameters
  message("\nValidating rendering parameters")
  message("---")
  
    # Input path
    message("1. Input path")
    if (length(ticq::retrieveFileList(inputPath = inputPath, fileExtension = "JSON")) == 0) {
      stop("Invalid 'inputPath': No available JSON files at the specified path")
    }
    print(inputPath)
    metadata <- ticq::extractMetadata(input = inputPath)
  
    # Output path
    message("\n2. Output directory path")
    if (is.null(outputDirectoryPath) || !is.character(outputDirectoryPath) || length(outputDirectoryPath) != 1 || outputDirectoryPath == "") {
      stop("Invalid 'outputDirectoryPath': Must be a non-NULL and non-empty character string")
    }
    print(outputDirectoryPath)
  
    # Historical data path
    message("\n3. Historical data path")
    if (!is.null(historicalDataPath)) {
      if (!is.character(historicalDataPath) || length(historicalDataPath) != 1 || historicalDataPath == "") {
        stop("Invalid 'historicalDataPath': Must be NULL or a non-empty character string of a RDS file path")
      } else if (!file.exists(historicalDataPath) || !grepl("\\.rds$", historicalDataPath, ignore.case = TRUE)) {
        stop("Invalid 'historicalDataPath': Must be an existing RDS file")
      }
    }
    print(historicalDataPath)
  
    # Target file path
    message("\n4. Target file path")
    if (!is.null(targetFilePath) && is.null(ticq::extractTargetFile(targetFilePath = targetFilePath))) {
      stop("Invalid 'targetFilePath': No available target file data found")
    }
    print(targetFilePath)
    
    # ANPC method library
    message("\n5. ANPC method library")
    if (!is.null(anpcMethodLibrary) && is.null(ticq::extractTargetFile(anpcMethodLibrary = anpcMethodLibrary))) {
      message("Invalid 'anpcMethodLibrary': No available target file data found (Setting default to NULL)")
      anpcMethodLibrary <- NULL
    }
    
    if (is.null(anpcMethodLibrary) && !is.na(metadata$method) && metadata$method %in% names(anpcChromatogramRegionData)) {
      message("Attempting to assign 'anpcMethodLibrary' from input metadata")
      if (!is.null(ticq::extractTargetFile(anpcMethodLibrary = metadata$method))) {
        message(paste("'anpcMethodLibrary': Setting new value to"), metadata$method)
        anpcMethodLibrary <- metadata$method
      }
    }
    print(anpcMethodLibrary)
    
    # Chromatogram region
    message("\n6. Chromatogram region")
    if (!is.null(chromatogramRegion) && (!is.list(chromatogramRegion) || !all(pattern %in% names(chromatogramRegion)))) {
      message("Invalid 'chromatogramRegion': Must be a list containing all required chromatogram region data of interests (Setting default to NULL)")
      chromatogramRegion <- NULL
    }
    
    if (is.null(chromatogramRegion) && !is.null(anpcMethodLibrary)) {
      message("Attempting to configure chromatogram region data using 'anpcMethodLibrary'")
      chromatogramRegion <- ticq::configureChromatogramRegion(
        massCalibrationStart = anpcChromatogramRegionData[[anpcMethodLibrary]]$massCalibrationStart,
        massCalibrationEnd = anpcChromatogramRegionData[[anpcMethodLibrary]]$massCalibrationEnd,
        washStart = anpcChromatogramRegionData[[anpcMethodLibrary]]$washStart
      )
      message(paste0("'chromatogramRegion': Data configured to ANPC method library (", anpcMethodLibrary, ")"))
    }
    print(chromatogramRegion)
  
    # Round decimal place
    message("\n7. Round decimal place")
    if (!is.null(roundDecimalPlace) && (!is.numeric(roundDecimalPlace) || length(roundDecimalPlace) != 1)) {
      stop("Invalid 'roundDecimalPlace': Must be NULL or a single numeric value")
    }
    print(roundDecimalPlace)
  
    # Sample anonymiser
    message("\n8. Metadata anonymiser")
    if (!is.logical(metadataAnonymiser) || length(metadataAnonymiser) != 1) {
      stop("Invalid 'metadataAnonymiser': Must be a single logical value")
    }
    print(metadataAnonymiser)
    
  message("---\n")

  # Render TICQ R markdown script
  message("Rendering TICQ...")
  title <- gsub("\\.json$", "", basename(inputPath), ignore.case = TRUE)
  rmarkdown::render(
    input = system.file("notebooks", "ticq.Rmd", package = "ticq"),
    output_format = "html_document",
    output_dir = outputDirectoryPath,
    output_file = paste0(title, ".html"),
    params = list(
      title = title,
      inputPath = inputPath,
      outputDirectoryPath = outputDirectoryPath,
      historicalDataPath = historicalDataPath,
      targetFilePath = targetFilePath,
      anpcMethodLibrary = anpcMethodLibrary,
      chromatogramRegion = chromatogramRegion,
      roundDecimalPlace = roundDecimalPlace,
      metadataAnonymiser = metadataAnonymiser
    )
  )
  message("Rendering complete!")
}
