#' Render TICQ Assessment
#' 
#' Perform TICQ assessment on MS spectral data acquired from JSON files generated using ExfilMS (https://github.com/vmalnathnambiar/exfilms) and render a HTML report of the assessment.
#' 
#' Metadata extraction and anonymisation only applicable to data acquired at the Australian National Phenome Centre (ANPC).
#' 
#' To evaluate extracted ions (target m/z) with TICQ, spectral data generated by ExfilMS should have undergone targeted spectra filtering during extraction to JSON using a target file or an in-house ANPC method library. The same target file or ANPC method library should be defined in TICQ for a comprehensive assessment. 
#' 
#' Historical spectral data used for comparison should have also undergone the same extraction/spectra filtering process previously as the current spectral data being assessed. Historical data should be made available in RDS format for reading.
#' Use ticq::extractExfilMS() to extract spectral data from ExfilMS generated JSON files to have the same data structure required for TICQ, and save data using saveRDS().
#' 
#' Chromatogram region can be configured using ticq::configureChromatogramRegion(). If no chromatogram region is provided, TICQ will attempt to configure the chromatogram region data using the ANPC method library defined.
#' 
#' @import httr
#' @import rmarkdown
#' 
#' @export
#' @param inputPath Input path to JSON files generated by ExfilMS: character
#' @param outputPath Output path to save HTML report and spectral data RDS output (Default: /path/to/current/working/directory/output/): character
#' @param historicalDataPath Historical data path containing spectral data for comparison (.rds format) (Default: NULL): NULL or character
#' @param targetFilePath Published to web URL or local path of the TSV formatted target file (Default: NULL, Options: Published to web URL or local file path): NULL or character
#' @param anpcMethodLibrary ANPC method library (Default: NULL, Options: "MS-AA-POS", "MS-HIL-POS", "MS-HIL-NEG", "MS-RP-POS" or "MS-RP-NEG"): NULL or character
#' @param chromatogramRegion A list containing the start and end time points of the different chromatogram regions of interest (Default: NULL, Options: ticq::configureChromatogramRegion()): NULL or list
#' @param roundDecimalPlace Number of decimal places for precision value rounding (Default: NULL): NULL or numeric
#' @param metadataAnonymiser Toggle to anonymise metadata (Default: FALSE, Options: TRUE or FALSE): logical
renderTICQ <- function(inputPath, outputPath = NULL, historicalDataPath = NULL, targetFilePath = NULL, anpcMethodLibrary = NULL, chromatogramRegion = NULL, roundDecimalPlace = NULL, metadataAnonymiser = FALSE) {
  # Chromatogram region data patterns and associated ANPC method library representation
  pattern <- c("prewash", "massCalibration", "analyte", "wash")
  anpcChromatogramRegionData <- list(
    "MS-AA-POS" = list(massCalibrationStart = 0, massCalibrationEnd = 0.3, washStart = 5),
    "MS-HIL-POS" = list(massCalibrationStart = 0, massCalibrationEnd = 0.7, washStart = 11),
    "MS-HIL-NEG" = list(massCalibrationStart = 0, massCalibrationEnd = 0.7, washStart = 11),
    "MS-RP-POS" = list(massCalibrationStart = 0, massCalibrationEnd = 0.7, washStart = 11),
    "MS-RP-NEG" = list(massCalibrationStart = 0, massCalibrationEnd = 0.7, washStart = 11)
  )
  
  # Validate parameters
  message("\nValidating rendering parameters")
  message("---")
  
    # Input path
    message("1. Input path")
    if (is.null(inputPath) || !is.character(inputPath)) {
      message("Unable to render TICQ: Invalid input path")
      return(invisible(NULL))
    } else if (!dir.exists(inputPath) && !file.exists(inputPath)) {
      message("Unable to render TICQ: Input path does not exist")
      return(invisible(NULL))
    } else if (length(ticq::retrieveFileList(inputPath = inputPath, fileExtension = "JSON")) == 0) {
      message("Unable to render TICQ: No available JSON files")
      return(invisible(NULL))
    }
    metadata <- ticq::extractMetadata(input = inputPath)
  
    # Output path
    message("\n2. Output path")
    if (is.null(outputPath) || !is.character(outputPath) || outputPath == "") {
      outputPath <- paste0(getwd(), "/output/")
      message(paste0("Invalid output path: Setting default (", outputPath, ")"))
    }
  
    # Historical data path
    message("\n3. Historical data path")
    if (!is.null(historicalDataPath) || !is.character(historicalDataPath)) {
      message("Invalid historical data path: Setting default (NULL)")
      historicalDataPath <- NULL
    } else if (!file.exists(historicalDataPath)) {
      message("Historical data path does not exist: Setting default (NULL)")
      historicalDataPath <- NULL
    } else if (!grepl("\\.rds$", historicalDataPath, ignore.case = TRUE)) {
      message("Invalid historical data format: Setting default (NULL)")
      historicalDataPath <- NULL
    }
  
    # Target file path
    message("\n4. Target file path")
    if (!is.null(targetFilePath) && 
        (!is.character(targetFilePath) || !(grepl("^(?:http|https)://[^ \"]+&output=tsv$|\\.tsv$", targetFilePath, ignore.case = TRUE)))) {
      message("Invalid target file format: Setting default (NULL")
      targetFile <- NULL
    } else if (!is.null(targetFilePath) && grepl("^(?:http|https)://[^ \"]+&output=tsv$", targetFilePath, ignore.case = TRUE)) {
      # Check response
      response <- tryCatch(httr::GET(targetFilePath), warning = function(w) NULL, error = function(e) NULL)
      if (is.null(response) && httr::status_code(response) != 200) {
        message("Target file unsuccessful HTTP request: Setting default (NULL)")
        targetFilePath <- NULL
      }
    } else if (!is.null(targetFilePath) && grep("\\.tsv$", targetFilePath, ignore.case = TRUE) && !file.exists(targetFilePath)) {
      message("Target file path does not exist: Setting default (NULL)")
      targetFilePath <- NULL
    }
    
    # ANPC method library
    message("\n5. ANPC method library")
    if (!is.null(anpcMethodLibrary) && (!is.character(anpcMethodLibrary) || !(anpcMethodLibrary %in% names(anpcChromatogramRegionData)))) {
      message("Invalid ANPC method library: Setting default (NULL)")
      anpcMethodLibrary <- NULL
    }
    
    # Chromatogram region
    message("\n6. Chromatogram region")
    if (!is.null(chromatogramRegion) && (!is.list(chromatogramRegion) || !all(pattern %in% names(chromatogramRegion)))) {
      message("Invalid chromatogram region format: Setting default (NULL)")
      chromatogramRegion <- NULL
    }
    
    if (is.null(chromatogramRegion) &&
        ((!is.null(anpcMethodLibrary) && anpcMethodLibrary %in% names(anpcChromatogramRegionData)) ||
         (!is.na(metadata$method) && metadata$method %in% names(anpcChromatogramRegionData)))) {
      message("Attempting to use associated ANPC method library chromatogram region data")
      method <- if (!is.null(anpcMethodLibrary) && anpcMethodLibrary %in% names(anpcChromatogramRegionData)) anpcMethodLibrary else metadata$method
      chromatogramRegion <- ticq::configureChromatogramRegion(
        massCalibrationStart = anpcChromatogramRegionData[[method]]$massCalibrationStart,
        massCalibrationEnd = anpcChromatogramRegionData[[method]]$massCalibrationEnd,
        washStart = anpcChromatogramRegionData[[method]]$washStart
      )
      message(paste0("Chromatogram region: Setting to associated ANPC method library (", method, ")"))
    }
  
    # Round decimal place
    message("\n7. Round decimal place")
    if (!is.null(roundDecimalPlace) && !is.numeric(roundDecimalPlace)) {
      message("Invalid round decimal place: Setting default (NULL)")
      roundDecimalPlace <- NULL
    }
  
  
    # Sample anonymiser
    message("\n8. Metadata anonymiser")
    if (!is.logical(metadataAnonymiser)) {
      message("Invalid metadata anonymiser: Setting default (FALSE)")
      metadataAnonymiser <- FALSE
    }
    
  message("---")
}

# # Load package
# ticq::loadPackage(packageList = c("rmarkdown"))
# 
# # Input data (Path to directory or JSON file to be processed)
# input <- "/path/to/input/directory/or/file.json"
# 
# # Extract metadata (if JSON file)
# metadata <- ticq::extractMetadata(input = input)
# 
# # Configure parameters (Dynamically based on input metadata - ANPC specific)
# # Output path
# outputDir <- paste0(getwd(), "/report/")
# 
# # Chromatogram region
# timepoint <- list("MS-AA-POS" = list(massCalStart = 0, massCalEnd = 0.3, washStart = 5),
#                   "MS-HIL-POS" = list(massCalStart = 0, massCalEnd = 0.7, washStart = 11),
#                   "MS-HIL-NEG" = list(massCalStart = 0, massCalEnd = 0.7, washStart = 11),
#                   "MS-RP-POS" = list(massCalStart = 0, massCalEnd = 0.7, washStart = 11),
#                   "MS-RP-NEG" = list(massCalStart = 0, massCalEnd = 0.7, washStart = 11))
# 
# # Check if method was extracted in the metadata and is one of the in-house ANPC method library
# if (!is.na(metadata$method) && metadata$method %in% names(timepoint)) {
#   timepoint <- timepoint[[metadata$method]]
#   chromatogramRegion <- ticq::configureChromatogramRegion(massCalStart = timepoint$massCalStart,
#                                                           massCalEnd = timepoint$massCalEnd,
#                                                           washStart = timepoint$washStart)
# } else {
#   chromatogramRegion <- NULL
#   metadata$method <- NULL
# }
# 
# 
# # Render TICQ R Markdown script
# rmarkdown::render(input = paste0(getwd(), "/notebook/ticq.Rmd"),
#                   output_format = "html_document",
#                   output_dir = outputDir,
#                   output_file = paste0(outputDir, 
#                                        gsub("\\.json$", "", basename(input), ignore.case = TRUE), 
#                                        ".html"),
#                   params = list(title = gsub("\\.json$", "", basename(input), ignore.case = TRUE),
#                                 input = input,
#                                 chromatogramRegion = chromatogramRegion,
#                                 targetFile = NULL,
#                                 anpcMethodLibrary = metadata$method,
#                                 roundDecimal = 4,
#                                 anonymiserStatus = FALSE))
# 
# # Clean environment
# rm(metadata, outputDir, timepoint)
