#' Render TICQ Assessment
#' 
#' Perform TICQ assessment on MS spectral data acquired from JSON files generated using \href{https://github.com/vmalnathnambiar/exfilms}{ExfilMS}
#' and render a HTML report of the assessment.
#' 
#' Metadata extraction and anonymisation only applicable to data acquired at the Australian National Phenome Centre (ANPC).
#' 
#' To evaluate extracted ions (target m/z) with TICQ, spectral data generated by ExfilMS should have undergone targeted spectra filtering during the extraction process into JSON using a target file or an in-house ANPC method library.
#' The same target file or ANPC method library should be specified in TICQ for a comprehensive assessment.
#' 
#' Historical spectral data used for comparison should have also undergone the same extraction/spectra filtering process previously as the current spectral data being assessed.
#' 
#' @import httr
#' @import rmarkdown
#' 
#' @export
#' @param inputPath Input path to JSON files generated by ExfilMS: character
#' @param outputDirectoryPath Output directory path to save HTML report and spectral data RDS output (Default: /output/folder/in/current/working/directory/): character
#' @param historicalDataPath Historical data path to be used for spectral data comparison (Default: NULL, Options: Local file path of a RDS file): NULL or character
#' @param targetFilePath Target file path (Default: NULL, Options: Published to web URL or local file path of a TSV file): NULL or character
#' @param anpcMethodLibrary ANPC method library (Default: NULL, Options: "MS-AA-POS", "MS-HIL-POS", "MS-HIL-NEG", "MS-RP-POS" or "MS-RP-NEG"): NULL or character
#' @param chromatogramRegion A list containing the start and end time points of the different chromatogram regions of interest (Default: NULL, Options: ticq::configureChromatogramRegion()): NULL or list
#' @param roundDecimalPlace Number of decimal places for precision value rounding (Default: NULL): NULL or numeric
#' @param metadataAnonymiser Toggle to anonymise metadata (Default: FALSE, Options: TRUE or FALSE): logical
renderTICQ <- function(inputPath, outputDirectoryPath = paste0(getwd(), "/output/"), historicalDataPath = NULL, targetFilePath = NULL, anpcMethodLibrary = NULL, chromatogramRegion = NULL, roundDecimalPlace = NULL, metadataAnonymiser = FALSE) {
  # Chromatogram region data patterns and associated ANPC method library representation
  pattern <- c("prewash", "massCalibration", "analyte", "wash")
  anpcChromatogramRegionData <- list(
    "MS-AA-POS" = list(massCalibrationEnd = 0.3, washStart = 5),
    "MS-HIL-POS" = list(massCalibrationEnd = 0.7, washStart = 11),
    "MS-HIL-NEG" = list(massCalibrationEnd = 0.7, washStart = 11),
    "MS-RP-POS" = list(massCalibrationEnd = 0.7, washStart = 11),
    "MS-RP-NEG" = list(massCalibrationEnd = 0.7, washStart = 11)
  )
  
  # Validate parameters
  message("\nValidating rendering parameters")
  message("---")
  
    # Input path
    message("1. Input path")
    if (length(ticq::retrieveFileList(inputPath = inputPath, fileExtension = "JSON")) == 0) {
      stop("Invalid 'inputPath': No available JSON files")
    }
    print(inputPath)
    inputMetadata <- ticq::extractMetadata(input = inputPath)
  
    # Output path
    message("\n2. Output directory path")
    if (is.null(outputDirectoryPath) || length(outputDirectoryPath) == 0) {
      outputDirectoryPath <- paste0(getwd(), "/output/")
      message(paste0("Setting default path (", outputDirectoryPath, ")"))
    } else if (length(outputDirectoryPath) != 1 || !is.character(outputDirectoryPath) || is.na(outputDirectoryPath) || outputDirectoryPath == "") {
      stop("Invalid 'outputDirectoryPath': Must be non-empty character string of length 1 representing a directory path")
    } else if (substring(outputDirectoryPath, nchar(outputDirectoryPath)) != "/") {
      outputDirectoryPath <- paste0(outputDirectoryPath, "/")
    }
    
    if (!dir.exists(outputDirectoryPath)) {
      dir.create(outputDirectoryPath, recursive = TRUE)
    }
    print(outputDirectoryPath)
  
    # Historical data path
    message("\n3. Historical data path")
    if (!is.null(historicalDataPath)) {
      if (length(historicalDataPath) != 1 || !is.character(historicalDataPath) || !grepl("\\.rds$", historicalDataPath, ignore.case = TRUE)) {
        stop("Invalid 'historicalDataPath': Must be NULL or non-empty character string of length 1 representing a RDS file path")
      } else if (!file.exists(historicalDataPath)) {
        stop("Invalid 'historicalDataPath': No available RDS file")
      }
    }
    print(historicalDataPath)
  
    # Target file path
    message("\n4. Target file path")
    if (!is.null(targetFilePath) && is.null(ticq::extractTargetFile(targetFilePath = targetFilePath))) {
      stop("Invalid 'targetFilePath': No available target file data")
    }
    print(targetFilePath)
    
    # ANPC method library
    message("\n5. ANPC method library")
    if (is.null(anpcMethodLibrary)) {
      if (inputMetadata$method %in% names(anpcChromatogramRegionData)) {
        message("Attempting to set method library based on input metadata")
        if (!is.null(ticq::extractTargetFile(anpcMethodLibrary = inputMetadata$method))) {
          message(paste0("Setting new value (", inputMetadata$metadata, ")"))
          anpcMethodLibrary <- inputMetadata$method
        } else {
          message("Unsuccessful attempt: No available target file data")
        }
      }
    } else if (!is.null(anpcMethodLibrary) && is.null(ticq::extractTargetFile(anpcMethodLibrary = anpcMethodLibrary))) {
      stop("Invalid 'anpcMethodLibrary': No available target file data")
    }
    print(anpcMethodLibrary)
    
    # Chromatogram region
    message("\n6. Chromatogram region")
    if (!is.null(chromatogramRegion) &&
        (length(chromatogramRegion) != 4 || !is.list(chromatogramRegion) || !all(pattern %in% names(chromatogramRegion)))) {
      message("Invalid 'chromatogramRegion': Must be a list containing the start and end time points of 4 required region data")
      if (!all(pattern %in% names(chromatogramRegion))) {
        message(paste0(
          "Invalid 'chromatogramRegion': Missing data (",
          paste(pattern[!pattern %in% names(chromatogramRegion)], collapse = ", "),
          ")"
        ))
      }
      message("Setting default value (NULL)")
      chromatogramRegion <- NULL
    }
    
    if (is.null(chromatogramRegion) && !is.null(anpcMethodLibrary) && anpcMethodLibrary %in% names(anpcChromatogramRegionData)) {
      message(paste("Setting new region data (based on ANPC", anpcMethodLibrary, "method library)"))
      chromatogramRegion <- ticq::configureChromatogramRegion(
        massCalibrationEnd = anpcChromatogramRegionData[[anpcMethodLibrary]]$massCalibrationEnd,
        washStart = anpcChromatogramRegionData[[anpcMethodLibrary]]$washStart
      )
    }
    print(chromatogramRegion)
  
    # Round decimal place
    message("\n7. Round decimal place")
    if (!is.null(roundDecimalPlace) && (length(roundDecimalPlace) != 1 || !is.numeric(roundDecimalPlace))) {
      stop("Invalid 'roundDecimalPlace': Must be NULL or numerical value of length 1")
    }
    print(roundDecimalPlace)
  
    # Sample anonymiser
    message("\n8. Metadata anonymiser")
    if (length(metadataAnonymiser) != 1 || !is.logical(metadataAnonymiser) || is.na(metadataAnonymiser)) {
      stop("Invalid 'metadataAnonymiser': Must be logical value of length 1 (TRUE or FALSE)")
    }
    print(metadataAnonymiser)
    
  message("---\n")

  # Render TICQ R markdown script
  message("Rendering TICQ...")
  title <- gsub("\\.json$", "", basename(inputPath), ignore.case = TRUE)
  rmarkdown::render(
    input = system.file("notebooks", "ticq.Rmd", package = "ticq"),
    output_format = "html_document",
    output_dir = outputDirectoryPath,
    output_file = paste0(title, ".html"),
    params = list(
      title = title,
      inputPath = inputPath,
      outputDirectoryPath = outputDirectoryPath,
      historicalDataPath = historicalDataPath,
      targetFilePath = targetFilePath,
      anpcMethodLibrary = anpcMethodLibrary,
      chromatogramRegion = chromatogramRegion,
      roundDecimalPlace = roundDecimalPlace,
      metadataAnonymiser = metadataAnonymiser
    )
  )
  message("Rendering complete!")
}
